### ISSUE TITLE
Type error for V0.7.0

### ISSUE THREAD

**Issue by winston0410** [TylorS/snowpack-plugin-hash#2] opened 2020-12-11 02:24 UTC
I got this error after upgrading from 0.5.4 to 0.7.0.

```
TypeError [ERR_INVALID_ARG_TYPE]: The
 "data" argument must be of type string or an instance of Bu
ffer, TypedArray, or DataView. Received null
```
I guess it is related with the new baseurl support. Hope this would be helpful.

My config:
```
    ['snowpack-plugin-hash', {
      hashLength: 4,
      assetManifest: ASSET_MANIFEST //'asset-manifest.json'
    }],
```

**Comment by TylorS** [comment] 2020-12-11 20:31
Hey @winston0410, sorry for breaking your build! 

It could possibly be related to the source map improvements of 0.6 or the baseUrl support in 0.7. It's unclear to me just yet from that specific part of the error which it's coming from. Do you happen to have the full stack trace?

**Comment by winston0410** [comment] 2020-12-13 06:00
Is alright @TylorS. Your plugin still serve my build well in 0.5.4 👍 

I cannot output the full error, even if I use `snowpack build --verbose`. Not 100% sure though, but based on my own experience, using `try()` and `catch()` will output the full error. I found out that snowpack occasionally hide the trace of an error coming from a plugin.

**Comment by winston0410** [comment] 2020-12-13 10:08
And I can confirm that the issue also appears in 0.6.0.

**Comment by TylorS** [comment] 2020-12-13 20:39
Hey @winston0410 , thanks for testing that. Its most likely related to sourceMaps then. Do you currently have sourceMaps:true for installOptions or buildOptions?

**Comment by winston0410** [comment] 2020-12-14 06:24
Yes I have `sourceMap: true` for both `installOptions` and `buildOptions` right now.

**Comment by TylorS** [comment] 2020-12-14 16:44
Is that the exact spelling you have in your snowpack config? I believe it should be `sourceMaps: true` for [build options](https://www.snowpack.dev/reference/configuration#buildoptions.sourcemaps-%7C-boolean-%7C-default%3A-false) and `sourceMap: true` for [install options](https://www.snowpack.dev/reference/configuration#installoptions.sourcemap-boolean) which is extra confusing

**Comment by TylorS** [comment] 2020-12-14 20:53
👋 I ran into the same error working on another snowpack plugin..I was able to fix it in my case, but since its so opaque I'm not 100% sure it'll help your case. When you get a moment, if you could try out `0.7.1` hopefully we'll have some fixes

**Comment by winston0410** [comment] 2020-12-15 04:39
Hi I have just upgraded and tested with 0.7.1, with all other plugins disabled, and I got this error:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "
data" argument must be of type string or an instance of Buffer
, TypedArray, or DataView. Received null
```

But I have upgraded snowpack to 3.0.0 rc-2 when I test this. I will downgrade snowpack and test it again when I have time.

**Comment by TylorS** [comment] 2020-12-16 18:50
I tried updating the app I've been testing this out in to 3.0 and I got some new errors, but not the same one as you're encountering

**Comment by TylorS** [comment] 2020-12-16 18:55
Do you think it'd be at all possible to share a minimal reproduction of the issue as a github repo or something of the sorts? I'd like to help, but I'm kinda shooting into the dark still

**Comment by TylorS** [comment] 2020-12-17 17:29
Another question... are you using TypeScript?

**Comment by winston0410** [comment] 2020-12-18 05:37
@TylorS I am able to reproduce the issue with this repo: https://github.com/winston0410/fix-hash

I hope this would be helpful!

**Comment by TylorS** [comment] 2020-12-18 14:14
Many thanks, I'll try to give this a test this weekend and see what I can find with some try/catches

**Comment by TylorS** [comment] 2020-12-24 02:04
Hey @winston0410 ! I think I might have found the piece of (bad 😬) code that is causing this is. In diffMagicString.ts there's an unsafe null coercion that I assumed would be safe. It seems like it would also cause this kind of error, so it seems probable.

I'll try to rework things around the safe version of this over the holidays when I've got some free time.

Happy holidays!

**Comment by winston0410** [comment] 2020-12-24 08:09
Hi @TylorS ! Glad to know that you found the where the error coming from. I hope this bug would be easy to fix, and I wish you a happy holiday too!

**Comment by noahlh** [comment] 2021-01-06 06:12
Hello @TylorS!  Just a quick +1 here ... I'm having this issue on a new snowpack project I'm testing out.  Not urgent but if you have any thoughts on fixes, do let me know!

**Comment by TylorS** [comment] 2021-01-06 13:46
@noahlh Thanks for reaching out. Unfortunately I am pretty sure that the sourceMaps code i have now is just overly complex and leads to strange errors. If you check out issue #3 about V1 brainstorming I've got an in progress attempt to rewrite this tool with what I know now.

**Comment by TylorS** [comment] 2021-01-08 21:07
Hey @winston0410 @noahlh, I've just released v0.8.0 with the rewrite I was talking about in #3. Let me know when y'all have had a moment to test it out, thanks!


If y'all both report having better luck this time around, I'll probably bump up to v1

**Comment by TylorS** [comment] 2021-01-18 04:41
@winston0410 I'm fairly confident your specific issue should be resolved now. I made a PR to your github repo with the bug reproduction 🙏 

@noahlh If you could also update to the latest version to try things out, that'd be greatly appreciated!

**Comment by noahlh** [comment] 2021-01-18 04:53
@TylorS Thank you so much for the updates!  Sorry haven't had a chance to dive back into this, but I'm excited to check out the latest version on my project.  Planning to dive in this week and will report back.

**Comment by TylorS** [comment] 2021-01-29 02:39
I'm going to go ahead and close this issue out, because I'm pretty sure the original issue has been sorted out. Sourcemaps have been greatly simplified in the latest versions of this plugin, and can even be disabled with snowpack's buildOptions `sourcemap: false` in your snowpack config or `sourceMap: false` in this plugin's options as a general workaround if there were issues or they were never really needed.

As always, feel free to open any additional issues or reopening this one if any problems arise

**Closed as completed by TylorS** 2021-01-29 02:39 UTC
